---
# using absolute path for s3 object starting from ansibles root because of
# https://github.com/ansible/ansible-modules-core/issues/1907
#- s3: bucket={{ bucket }} object=dcos-template.json src=/vagrant/provisioning/roles/cloudformation/files/dcos-template.json mode=put
- name: Copy initial files into S3 bucket
  local_action: aws_s3 bucket={{ bucket }} object=dcos-template.json src=/home/jedi/gitlab/smack/intro-to-dcos/provisioning/roles/cloudformation/files/dcos-template.json mode=put aws_access_key={{ aws_access_key }} aws_secret_key={{ aws_secret_key }} 


- name: launch ansible cloudformation example
  cloudformation:
    stack_name: "{{ stackName }}"
    state: "present"
    region: "{{ aws_region }}"
    template_url: "https://s3.amazonaws.com/{{ bucket }}/dcos-template.json"
    template_parameters:
      KeyName: "{{ keyName }}"
      PublicSlaveInstanceCount: "{{ publicSlaveInstanceCount }}"
      SlaveInstanceCount: "{{ slaveInstanceCount }}"
      OAuthEnabled: "{{ oauthEnabled }}"
    tags:
      Stack: "ansible-cloudformation"

- aws_s3: bucket={{ bucket }} mode=delete
